Add `isSatisfiedByAny()` to `Range` and `RangesList`
semver4j/semver4j pull request #108
Opened 2022-12-02 20:08 UTC by sschuberth

These convenience methods check whether a range was created in such a way that it matches any version.

2022-12-02 20:33 UTC, piotrooo commented
Many thanks 🙏 
I'll review this when I'll be on PC.

2022-12-03 18:04 UTC, piotrooo requested changes

2022-12-03 18:04 UTC, piotrooo commented on src/main/java/org/semver4j/Range.java
> +        return rangeVersion.isEqualTo("0.0.0") && rangeOperator == RangeOperator.GTE;
Maybe we should extract this "magic" string `0.0.0` to some const. We use it in https://github.com/semver4j/semver4j/blob/87d98cabd6fde09efe01138622468b11e8c52566/src/main/java/org/semver4j/internal/range/processor/GreaterThanOrEqualZeroProcessor.java#L20

I propose in `Semver` class:

https://github.com/semver4j/semver4j/blob/87d98cabd6fde09efe01138622468b11e8c52566/src/main/java/org/semver4j/Semver.java#L17-L19

add const:

```
public static final Semver ZERO = new Semver("0.0.0");
```

This allows us to use it in `isSatisfiedByAny` method:

```
public boolean isSatisfiedByAny() {
    return rangeVersion.isEqualTo(ZERO) && rangeOperator == RangeOperator.GTE;
}
```

And in the `GreaterThanOrEqualZeroProcessor` like this:

```
return format(Locale.ROOT, "%s%s", GTE.asString(), ZERO);
```

2022-12-03 18:04 UTC, piotrooo commented on src/main/java/org/semver4j/RangesList.java
> +            .allMatch(range -> range.isSatisfiedByAny());
Use fluent method in new line and replace lambda with method reference:

```
public boolean isSatisfiedByAny() {
    return rangesList.stream()
        .flatMap(List::stream)
        .allMatch(Range::isSatisfiedByAny);
}
```

2022-12-03 18:04 UTC, piotrooo commented on src/test/java/org/semver4j/RangeTest.java
> +        Range range = new Range("0.0.0", GTE);
When we extract a `ZERO` const, could be used here.

2022-12-07 08:19 UTC, piotrooo commented
@sschuberth gently ping :smile:

2022-12-07 09:09 UTC, sschuberth commented
> @sschuberth gently ping 😄

Sorry, I was busy at my day job.

2022-12-07 11:04 UTC, piotrooo submitted a review, later dismissed

2022-12-07 11:37 UTC, sschuberth commented
@piotrooo I had to adjust the initialization order of the static `ZERO` field.

2022-12-07 13:13 UTC, sschuberth commented
> @piotrooo I had to adjust the initialization order of the static `ZERO` field.

Yet again 😒

2022-12-07 16:16 UTC, merged

2022-12-07 16:17 UTC, piotrooo commented
@sschuberth thanks. I've merge it with errors but I need to fix it by my own.