Replace nullness annotations with JSpecify
semver4j/semver4j pull request #309
Opened 2024-11-25 17:51 UTC by mk868

Replace nullness annotations with JSpecify.
Related issue #308 

Changes in this PR:

- pom.xml: `org.jetbrains:annotations` replaced with `org.jspecify:jspecify`
- Replace `@NonNull` annotations with `@NullMarked` annotation - to mark all types in the class scope as non-null by default ([docs](https://jspecify.dev/docs/user-guide/#nullmarked))
- Move `@Nullable` annotations to types
  - `@Nullable public static Semver` -> `public static @Nullable Semver`
  - `@Nullable final String version` -> `final @Nullable String version`
- Removed single use of the `org.jetbrains.annotations.ApiStatus.AvailableSince` annotation - we have same info in the JavaDoc `@since` tag
- Fixed invalid annotation in the `src/test/java/org/semver4j/internal/range/processor/ProcessorTest.java` file (when we implement an interface, we should keep the same type annotations)

2024-12-17 07:53 UTC, piotrooo requested changes
Firstly, thanks for your work!
Secondly, sorry for the late response 😭

Regarding the code - one thing: for the return method, I prefer placing the annotation at the method level rather that next to the return type.

This is described in the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.8.5.2-class-annotation-style).

Use:

```
@Nullable
public static String coerce(@NotNull final String version)
```

Instead:

```
public static @Nullable String coerce(final String version)
```

2024-12-17 16:33 UTC, mk868 commented
Sure - javac will generate exactly the same byte code for `@Nullable public static String coerce(...)` and `public static @Nullable String coerce(...)`.
I'll push changes soon


Worth to mention: JSpecify's `@Nullness` and `@NotNull`  are `TYPE_USE` annotations - and [Google Style](https://google.github.io/styleguide/javaguide.html#s4.8.5.1-type-use-annotation-style) describes how to use them, but in this case it really doesn't matter

2024-12-18 20:20 UTC, mk868 commented
Okay, I moved the `@Nullable` annotations before the methods, as requested

2024-12-18 22:22 UTC, piotrooo approved these changes

2024-12-18 22:22 UTC, merged