Add NullAway checks
semver4j/semver4j pull request #317
Opened 2024-12-30 16:06 UTC by mk868

Related: https://github.com/semver4j/semver4j/issues/312

Changes in this PR:

- A new Maven profile `nullaway` added
- Analysis with Java 23 added to the CI - the latest version of java contains the most fixes

2025-01-06 22:21 UTC, xenoterracide commented
I'm not certain that it's a good idea to use jspecify mode yet, I think that's pretty significantly under development. YMMV, but jspecify mode isn't needed just because you're using those annotations. On the other hand, if it works...

2025-01-07 16:25 UTC, mk868 commented
Thank you for pointing that out!
I'm aware that the logic under this flag is still under development.
For me, enabling JSpecifyMode is a way to contribute to the community, any unexpected behavior we encounter in NullAway can be reported to its creators to help improve the tool.
Since this is a build-time tool, it's safe for the semver4j project - if critical issues occur with the tool, we can simply remove the `-XepOpt:NullAway:JSpecifyMode=true` flag.

@piotrooo WDYT?

2025-01-21 06:01 UTC, piotrooo requested changes

2025-01-21 06:01 UTC, piotrooo commented on .github/workflows/ci.yml
> +          java-version: 23
I'm considering one thing here: should the version be set to 23?

The policy for supported Java versions only includes the currently supported LTS. I'm thinking about moving the version to 21 to be fully compliant with this policy.

2025-01-21 16:30 UTC, mk868 commented on .github/workflows/ci.yml
> +          java-version: 23
The latest Java version (currently Java 23) is actively maintained by OpenJDK and includes the most recent bug fixes (in the context of NullAway, we are interested in the latest fixes for javac).

LTS releases, such as 8, 11, 17 and 21, receive backports of some (not all!) bug fixes from the latest version.
For example, this pull request https://github.com/uber/NullAway/pull/1034 shows the functionality that works only when running with Java 23+.

2025-01-21 19:57 UTC, merged