feat: SEM-48 add validation to protect int overflow
semver4j/semver4j pull request #74
Opened 2022-08-27 11:02 UTC by Koziolek

Add validation of version value. If it's to big to be int, then throws. Still thinking about proper support of very big ints without api breaking changes.

2022-08-27 14:03 UTC, piotrooo requested changes
Thanks!
Fix a couple of details and I'll merge it.

2022-08-27 14:03 UTC, piotrooo commented on src/main/java/org/semver4j/internal/StrictParser.java
```
import static java.lang.Integer.parseInt;
```
looks like unnecessary import right now.

2022-08-27 14:03 UTC, piotrooo commented on src/test/java/org/semver4j/internal/StrictParserTest.java
> +
Some unnecessary blank line.

2022-08-30 06:08 UTC, piotrooo commented
Ping @Koziolek.

2022-09-01 14:48 UTC, Koziolek commented
Pong @piotrooo :)

2022-09-01 15:58 UTC, piotrooo approved these changes

2022-09-01 15:59 UTC, merged

2022-09-01 15:59 UTC, piotrooo commented
Many thanks!
Merged.

2022-09-01 16:00 UTC, piotrooo commented
Closes #48